spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/maoweixy/spring-cloud-learning
          searchPaths: config-repository
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/